M48
; DRILL file {KiCad 7.0.9} date Mon Jan 15 23:30:57 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-15T23:30:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X2.66Y-2.34
X4.465Y-2.1
X4.8421Y-2.4465
X4.8421Y-2.6741
X4.91Y-2.0575
X4.91Y-2.19
T0
M30
