M48
; DRILL file {KiCad 7.0.9} date Wed Dec 20 20:28:41 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-20T20:28:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X4.82Y-2.02
X4.82Y-2.14
X4.82Y-2.27
X4.8421Y-2.4465
X4.8421Y-2.6741
T0
M30
